import React, { useEffect, useState } from "react";
import ReactQuill from "react-quill";
import "react-quill/dist/quill.snow.css";
import { blogAPI } from "../../api";
import "../../styles/blog-admin.css";

const blank = { title:"", slug:"", author:"Jadhavar International School", description:"", metaTitle:"", metaDescription:"", imageAlt:"", image:null, imagePreview:null };
const slugify = (value) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const baseUrl = (import.meta.env.VITE_API_URL || "").replace(/\/api\/?$/, "");
export default function BlogAdmin() {
 const [blogs,setBlogs]=useState([]),[form,setForm]=useState(blank),[editId,setEditId]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=()=>blogAPI.getAll().then(({data})=>setBlogs(data)); useEffect(()=>{load()},[]);
 const change=(key,value)=>setForm(f=>({...f,[key]:value,...(key==="title"&&!editId?{slug:slugify(value)}:{})}));
 const submit=async(e)=>{e.preventDefault();setBusy(true);setMessage("");try{const data=new FormData();Object.entries(form).forEach(([key,value])=>{if(value!==null&&key!=="imagePreview")data.append(key,value)}); editId?await blogAPI.update(editId,data):await blogAPI.create(data);setForm(blank);setEditId(null);setMessage("Article saved successfully.");load()}catch{setMessage("Unable to save the article. Please try again.")}finally{setBusy(false)}};
 const edit=(b)=>{setEditId(b._id);setForm({...blank,...b,image:null,imagePreview:b.image?`${baseUrl}${b.image}`:null});scrollTo({top:0,behavior:"smooth"})};
 const remove=async(id)=>{if(confirm("Delete this article?")){await blogAPI.delete(id);load()}};
 return <main className="blog-admin"><header><p>CONTENT MANAGEMENT</p><h1>{editId?"Edit article":"Write a new article"}</h1><span>Use the editor exactly as you would a Medium-style story. A cover image is optional.</span></header><form onSubmit={submit}><div className="admin-fields"><label>Article title<input required value={form.title} onChange={e=>change("title",e.target.value)} /></label><label>URL slug<input required value={form.slug} onChange={e=>change("slug",slugify(e.target.value))} /><small>Creates /blog/{form.slug||"your-article"}</small></label><label>Author<input value={form.author} onChange={e=>change("author",e.target.value)} /></label><label>Cover image (optional)<input type="file" accept="image/*" onChange={e=>{const image=e.target.files[0];change("image",image);change("imagePreview",image?URL.createObjectURL(image):null)}} /></label><label>Image alt text<input value={form.imageAlt} onChange={e=>change("imageAlt",e.target.value)} placeholder="Describe the image for readers and search engines" /></label></div>{form.imagePreview&&<img className="admin-preview" src={form.imagePreview} alt="Cover preview"/>}<label className="editor-label">Article content</label><ReactQuill theme="snow" value={form.description} onChange={value=>change("description",value)} modules={{toolbar:[["header",[2,3,false]],["bold","italic","underline","blockquote"],[{list:"ordered"},{list:"bullet"}],["link","image"],["clean"]]}} /><div className="admin-fields seo-fields"><label>SEO title<input value={form.metaTitle} onChange={e=>change("metaTitle",e.target.value)} placeholder="Defaults to article title" /></label><label>SEO description<textarea value={form.metaDescription} onChange={e=>change("metaDescription",e.target.value)} placeholder="A concise search result description" /></label></div>{message&&<p className="admin-message">{message}</p>}<div className="form-actions"><button disabled={busy}>{busy?"Saving…":editId?"Update article":"Publish article"}</button>{editId&&<button type="button" className="cancel" onClick={()=>{setEditId(null);setForm(blank)}}>Cancel</button>}</div></form><section className="admin-list"><h2>Published articles</h2>{blogs.map(b=><article key={b._id}>{b.image&&<img src={`${baseUrl}${b.image}`} alt=""/>}<div><h3>{b.title}</h3><p>/blog/{b.slug || "legacy article"}</p></div><button onClick={()=>edit(b)}>Edit</button><button className="delete" onClick={()=>remove(b._id)}>Delete</button></article>)}</section></main>;
}
